labels: [General]
body:
- type: markdown
  attributes: 
   value:
    ⚠️ This Community is not a support forum. Flagged accounts, account takeovers, billing issues, and two-factor authentication recovery can only be resolved via your [GitHub Support](https://support.github.com/contact) ticket. ⚠️

    Community Discussions team members are unable to assist with nor escalate your ticket, but we can assure you it is in the right place. It will be answered in the order it was received based on our team's resources and the amount of tickets ahead of yours.
- type: dropdown
  attributes:
    label: Select Topic Area
    description: What would you like to discuss?
    options:
      - "Question"
      - "Product Feedback"
      - "Bug"
      - "Show & Tell"
      - "General"
  validations:
    required: true
- type: textarea
  attributes:
    label: Body
    description: Start your discussion!
  validations:
    required: true
