labels: [Programming Help]
body:
- type: markdown
  attributes:
    value: Start your discussion!
  validations:
    required: true
- type: textarea
  attributes:
    label: Body
    description: Start your discussion!
  validations:
    required: true
- type: checkboxes
  attributes:
    label: I have read and understood this category's <a href="https://github.com/orgs/community/discussions/51384">guidelines</a> before making this post. 
    options:
      - label: 'Yes'
        required: true
