labels: [Programming Help]
body:
- type: markdown
  attributes: 
  validations:
    required: true
- type: textarea
  attributes:
    label: Body
    description: Start your discussion!
  validations:
    required: true
  - type: checkboxes
    attributes:
      label: I have read and understood this category's [guidelines](ttps://github.com/orgs/community/discussions/51384) before making this post. 
      options:
        - label: This one!
          required: true
          h
